/* ================================================
   chapter1_accept.js — 챕터 1 수락 루트
================================================ */
const SCRIPT_CH1_ACCEPT = [

  { type: 'scene', text: '서기관실 복도' },
  { type: 'line', speaker: 'narration', text: '엄마의 대화는 좀처럼 끝날 기미가 없다.' },
  { type: 'line', speaker: 'narration', text: '벽에 등을 기대고 팔짱을 낀다. 천장을 올려다본다. 금빛 문양이 새겨진 천장. 몇 번을 봤는지 모른다.' },
  { type: 'line', speaker: 'narration', text: '그때 복도 저편에서 발소리가 들린다.' },
  { type: 'line', speaker: 'narration', text: '크고, 거침없고, 왠지 신나 있는 발소리.' },
  { type: 'line', speaker: 'uriel',     text: '오, 가브리엘!' },
  { type: 'line', speaker: 'narration', text: '우리엘 언니다. 엄마를 발견하자 눈이 반짝이더니 거침없이 걸어온다. 저 걸음걸이는 언제 봐도 멈출 생각이 없어 보인다.' },
  { type: 'line', speaker: 'uriel',     text: '나 얘 데려갈게.' },
  { type: 'line', speaker: 'narration', text: '내 손목을 낚아챈다. 엄마가 입을 열기도 전에.' },
  { type: 'line', speaker: 'gabriel',   text: '야, 잠깐만——!' },
  { type: 'line', speaker: 'uriel',     text: '메타트론한테 얘기 다 들었어. 걱정 마.' },
  { type: 'line', speaker: 'narration', text: '뒤도 돌아보지 않는다. 언니의 보폭은 넓고 빠르다. 나는 반쯤 끌려가면서 발을 맞춘다.' },
  { type: 'line', speaker: 'gabriel',   text: '우리엘!! 아직 내 말이——!' },
  { type: 'line', speaker: 'narration', text: '모퉁이를 돈다. 엄마 목소리가 벽 너머로 사라진다.' },
  { type: 'line', speaker: 'narration', text: '언니는 그제야 속도를 줄인다.' },

  { type: 'scene', text: '에덴 훈련 구역으로 향하는 길' },
  { type: 'unlock', char: 'uriel' },
  { type: 'line', speaker: 'narration', text: '손목을 놓아준 건 한참 뒤였다. 복도가 탁 트인 통로로 바뀌고, 발 아래 돌바닥이 흙으로 바뀔 즈음.' },
  { type: 'line', speaker: 'uriel',     text: '메타트론이 뭐라디?' },
  { type: 'line', speaker: 'narration', text: '걸으면서 묻는다. 시선은 앞을 향한 채로.' },
  { type: 'line', speaker: 'player',    text: '가벼운 훈련이라고 하셨어요.' },
  { type: 'line', speaker: 'narration', text: '언니가 고개를 한 번 끄덕인다. 잠깐 침묵이 흐른다 싶더니.' },
  { type: 'line', speaker: 'narration', text: '푸흡.' },
  { type: 'line', speaker: 'narration', text: '웃음이 새어나온다. 참으려다 실패한 것 같은 소리였다.' },
  { type: 'line', speaker: 'uriel',     text: '분명 재밌을 거야!' },
  { type: 'line', speaker: 'narration', text: '고개를 돌려 나를 본다. 눈이 반짝인다. 이 표정은 알고 있다. 뭔가 신나는 게 생겼을 때 나오는 얼굴이다.' },
  { type: 'line', speaker: 'player',    text: '…언니 기준으로요?' },
  { type: 'line', speaker: 'uriel',     text: '당연하지.' },
  { type: 'line', speaker: 'narration', text: '한 치의 망설임도 없다. 전혀 안심이 안 된다.' },

  { type: 'scene', text: '훈련 구역' },
  { type: 'line', speaker: 'narration', text: '탁 트인 공간이다. 에덴 외곽, 지붕 없는 훈련장.' },
  { type: 'line', speaker: 'narration', text: '발 아래 단단한 흙바닥. 저 끝까지 거리가 꽤 된다. 그냥 보기만 해도 숨이 찰 것 같다.' },
  { type: 'line', speaker: 'uriel',     text: '오늘은 체력 훈련이야!' },
  { type: 'line', speaker: 'narration', text: '팔짱을 끼고 가슴을 편다. 의기양양 그 자체다.' },
  { type: 'line', speaker: 'uriel',     text: '뭐해? 뛰어. 저 끝까지 갔다 와.' },
  { type: 'line', speaker: 'player',    text: '지금 바로요?' },
  { type: 'line', speaker: 'uriel',     text: '응.' },
  { type: 'line', speaker: 'narration', text: '뛴다.' },
  { type: 'line', speaker: 'narration', text: '바람이 귓가를 스치고, 발이 흙을 차고, 숨이 금방 올라온다. 끝에 닿아서 돌아보니 언니가 저 멀리서 손을 흔들고 있다. 신나게.' },
  { type: 'line', speaker: 'narration', text: '달려서 돌아간다. 무릎이 조금 흔들린다. 숨을 고를 틈도 없이 언니가 나를 내려다본다.' },
  { type: 'line', speaker: 'uriel',     text: '응? 뭐해? 더 뛰어야지.' },
  { type: 'line', speaker: 'narration', text: '나는 그때 직감했다. 오늘 죽었다.' },
  { type: 'line', speaker: 'narration', text: '두 바퀴, 세 바퀴. 언니는 표정 하나 안 변한다. 오히려 볼수록 신이 나 보인다.' },
  { type: 'line', speaker: 'narration', text: '네 바퀴째. 다리가 제멋대로 풀리기 시작한다. 발이 땅을 제대로 못 짚는다.' },
  { type: 'line', speaker: 'player',    text: '헉… 헉… 언니, 잠깐만요——' },
  { type: 'line', speaker: 'uriel',     text: '멈춰.' },
  { type: 'line', speaker: 'narration', text: '허락이 떨어지자마자 멈춘다. 무릎에 손을 짚고 고개를 숙인다. 바닥이 흔들리는 건지 내가 흔들리는 건지 모르겠다.' },
  { type: 'line', speaker: 'narration', text: '그때 발소리가 다가온다. 언니가 쪼그려 앉아서 내 눈높이에 얼굴을 들이민다. 가까운 거리에서 눈을 들여다본다.' },
  { type: 'line', speaker: 'uriel',     text: '나쁘지 않네. 생각보다.' },
  { type: 'line', speaker: 'narration', text: '숨을 헐떡이면서 언니를 올려다본다.' },
  { type: 'line', speaker: 'player',    text: '…그게 칭찬이에요?' },
  { type: 'line', speaker: 'uriel',     text: '응.' },
  { type: 'line', speaker: 'narration', text: '그러더니 툭, 머리를 한 번 두드리고 일어선다. 어린애 다루듯이. 근데 기분이 나쁘지 않다.' },
  { type: 'line', speaker: 'uriel',     text: '이제 자세 잡아봐. 다리 어깨 너비로.' },
  { type: 'line', speaker: 'player',    text: '지금요?!' },
  { type: 'line', speaker: 'uriel',     text: '응.' },
  { type: 'line', speaker: 'narration', text: '이미 시범을 보이고 있다. 설명보다 몸이 먼저다. 언니한테 "왜요"는 통하지 않는다. 그냥 하면 된다.' },
  { type: 'line', speaker: 'narration', text: '자세가 틀리면 말없이 다가와서 팔을 잡고, 어깨를 밀고, 발 위치를 발로 툭툭 건드려 고쳐준다.' },
  { type: 'line', speaker: 'narration', text: '잘 하면 "그래." 못 하면 "다시."' },
  { type: 'line', speaker: 'narration', text: '근데 이상하게 짜증은 나지 않는다.' },
  { type: 'stat', key: 'strength', delta: 1 },
  { type: 'stat', key: 'agility',  delta: 1 },

  { type: 'scene', text: '훈련 구역 — 저녁' },
  { type: 'line', speaker: 'narration', text: '어느새 하늘이 붉다. 해가 기울었다.' },
  { type: 'line', speaker: 'narration', text: '온몸이 납덩이 같다. 그냥 여기 드러누워버리고 싶다.' },
  { type: 'line', speaker: 'uriel',     text: '오늘은 여기까지.' },
  { type: 'line', speaker: 'narration', text: '언니가 물 한 잔을 툭 건넨다. 말없이 받아서 단숨에 들이켠다.' },
  { type: 'line', speaker: 'uriel',     text: '잘했어. 내일 또 와.' },
  { type: 'line', speaker: 'narration', text: '짧고 담백하다. 근데 그 두 글자가 생각보다 크게 들린다.' },
  { type: 'line', speaker: 'uriel',     text: '메타트론한테 보고는 네가 직접 해. 오늘 뭐 했는지.' },
  { type: 'line', speaker: 'narration', text: '고개를 끄덕이다가 잠깐 망설인다. 엄마한테도 알려야 할 것 같다.' },
  {
    type: 'choice',
    choices: [
      { text: '메타트론 서기관님께 먼저 보고한다', next: 'ch1_report_meta',    affinity: { metatron: 1 } },
      { text: '엄마한테 먼저 알리러 간다',         next: 'ch1_report_gabriel', affinity: { gabriel: 1 } },
    ],
  },
];
